from typing import Any, Callable, Iterable

import tensorflow as tf


class Tensor:
    def numpy(self) -> Any: ...


def constant(arraylike: Any, dtype: tf.DType = ..., shape: Iterable[int] | tf.TensorShape = ...) -> Tensor: ...
def stack(tensors: Iterable[Tensor]) -> Tensor: ...
def py_function(func: Callable[[Tensor], Tensor], inp: Any, Tout: tf.DType | Iterable[tf.DType], name: str = ...) -> Tensor: ...